# -*- coding: utf-8 -*-
"""BossAICode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-S6NBidLdDjCTI4c87LONtTcY6XnKQt
"""

import pandas as pd
df = pd.read_csv("./ND Analytics Challenge Dataset.csv")
df

df["datetime"] = pd.to_datetime(df["datetime"])
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['hour'] = df['datetime'].dt.hour
df = df.drop(columns=['datetime'])
df["sum_distance_from_avg"] = df["sum_amount"] - df["avg_amount_per_user"]
df["hour_0_thru_13"] = df["hour"] <= 13
df

import scipy.stats as stats
df["sum_amount_zscore"] = stats.zscore(df["sum_amount"])
df["avg_amount_zscore"] = stats.zscore(df["avg_amount_per_user"])
df["distance_zscore"] = stats.zscore(df["sum_distance_from_avg"])
df

df["sum_distance_from_avg"].describe()

df["sum_amount"].describe()

df["avg_amount_per_user"].describe()

# selecting rows based on condition
anomaly_df = df[df["anomaly"] == 1]

print('\nResult dataframe :\n', anomaly_df)

# selecting rows based on condition
normal_df = df[df["anomaly"] == 0]

print('\nResult dataframe :\n', normal_df)

anomaly_df["sum_amount"].describe()

normal_df["sum_amount"].describe()

anomaly_df["avg_amount_per_user"].describe()

normal_df["avg_amount_per_user"].describe()

anomaly_df["sum_distance_from_avg"].describe()

normal_df["sum_distance_from_avg"].describe()

import numpy as np

X = np.stack((df["anomaly"], df["distance_zscore"]), axis=0)
print("corrcoef =",np.corrcoef(X)[0, 1])

import numpy as np

X = np.stack((df["anomaly"], df["avg_amount_zscore"]), axis=0)
print("corrcoef =",np.corrcoef(X)[0, 1])

import numpy as np

#X = np.stack((df["anomaly"], df["hour"]), axis=0)
#print("corrcoef =",np.corrcoef(X)[0, 1])

#test_df = df[df["hour"] < 16]

ct = pd.crosstab(df["anomaly"], df["hour"], margins=True)
ct
chi2, p, dof, ex = stats.chi2_contingency(ct)
print("chi square =", chi2)

"""*Model Training*"""

df.columns.to_list()

from sklearn import preprocessing
le = preprocessing.LabelEncoder()

df_encoded = df.copy()
df_encoded["anomaly"] = le.fit_transform(df_encoded["anomaly"])
df_encoded["year"] = le.fit_transform(df_encoded["year"])
df_encoded["month"] = le.fit_transform(df_encoded["month"])
df_encoded["hour"] = le.fit_transform(df_encoded["hour"])
df_encoded["hour_0_thru_13"] = le.fit_transform(df_encoded["hour_0_thru_13"])

labels = df_encoded["anomaly"]
features = df_encoded.drop(columns=['anomaly',
 'sum_amount_zscore',
 'avg_amount_zscore',
 'distance_zscore', 'sum_distance_from_avg'])

df_encoded.to_csv('credit_anomaly.csv', index=False)

print(features)

print(labels)

#from sklearn.model_selection import train_test_split

#X_train, X_test, y_train, y_test = train_test_split(features, labels, stratify = y, test_size=0.2, random_state=123)

#X_train.append(x_train)
#X_test.append(x_test)
#Y_train.append(y_train)
#Y_test.append(y_test)

from sklearn import metrics
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB, CategoricalNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neural_network import MLPClassifier

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.4, random_state=123)

clf_knn = KNeighborsClassifier()
clf_id3 = tree.DecisionTreeClassifier(criterion="entropy", max_depth=2)
clf_id3_overfit = tree.DecisionTreeClassifier(criterion="entropy")
clf_cart = tree.DecisionTreeClassifier(max_depth=2)
clf_bayes = CategoricalNB()
clf_rbf = SVC()
clf_forest = RandomForestClassifier()
clf_boost = AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=2), random_state=21)
clf_mlp = MLPClassifier(hidden_layer_sizes=(10,3,), max_iter=1000, tol=0.003, random_state=42)

clf_knn.fit(X_train, y_train)
clf_id3.fit(X_train, y_train)
clf_id3_overfit.fit(X_train, y_train)
clf_cart.fit(X_train, y_train)
clf_bayes.fit(X_train, y_train)
clf_rbf.fit(X_train, y_train)
clf_forest.fit(X_train, y_train)
clf_boost.fit(X_train, y_train)
clf_mlp.fit(X_train, y_train)

print("F1:")
print("- KNN:", metrics.f1_score(y_test, clf_knn.predict(X_test)))
print("- ID3:", metrics.f1_score(y_test, clf_id3.predict(X_test)))
print("- ID3 (overfitting):", metrics.f1_score(y_test, clf_id3_overfit.predict(X_test)))
print("- CART:", metrics.f1_score(y_test, clf_cart.predict(X_test)))
print("- Naive Bayes:", metrics.f1_score(y_test, clf_bayes.predict(X_test)))
print("- RBF Kernel SVC:", metrics.f1_score(y_test, clf_rbf.predict(X_test)))
print("- Random Forest:", metrics.f1_score(y_test, clf_forest.predict(X_test)))
print("- AdaBoost:", metrics.f1_score(y_test, clf_boost.predict(X_test)))
print("- MLP:", metrics.f1_score(y_test, clf_mlp.predict(X_test)))

print("Balanced Accuracy:")
print("- KNN:", metrics.balanced_accuracy_score(y_test, clf_knn.predict(X_test)))
print("- ID3:", metrics.balanced_accuracy_score(y_test, clf_id3.predict(X_test)))
print("- ID3 (overfitting):", metrics.balanced_accuracy_score(y_test, clf_id3_overfit.predict(X_test)))
print("- CART:", metrics.balanced_accuracy_score(y_test, clf_cart.predict(X_test)))
print("- Naive Bayes:", metrics.balanced_accuracy_score(y_test, clf_bayes.predict(X_test)))
print("- RBF Kernel SVC:", metrics.balanced_accuracy_score(y_test, clf_rbf.predict(X_test)))
print("- Random Forest:", metrics.balanced_accuracy_score(y_test, clf_forest.predict(X_test)))
print("- AdaBoost:", metrics.balanced_accuracy_score(y_test, clf_boost.predict(X_test)))
print("- MLP:", metrics.balanced_accuracy_score(y_test, clf_mlp.predict(X_test)))

def GetMetrics(TP, FP, TN, FN):
    print("Confusion matrix:")
    print("\t", "-"*15)
    print("\t", "| TP", TP, "| FN   ", FN, "|")
    print("\t", "| FP ", FP, "| TN", TN, "|")
    print("\t", "-"*15)

    accuracy = 1.0*(TP+TN) / (TP + FP + TN + FN)
    ### TODO 7: ###
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1 = (2 * precision * recall) / (precision + recall)

    print("Accuracy:", np.round(accuracy, 4))
    print("Precision:", np.round(precision, 4))
    print("Recall:", np.round(recall, 4))
    print("F1:", np.round(f1, 4))

from sklearn.metrics import confusion_matrix

print("- KNN:")
pred = metrics.confusion_matrix(y_test, clf_knn.predict(X_test))
y_pred_knn = clf_knn.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- ID3:")
pred = metrics.confusion_matrix(y_test, clf_id3.predict(X_test))
y_pred_id3 = clf_id3.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- ID3 (overfitting):")
pred = metrics.confusion_matrix(y_test, clf_id3_overfit.predict(X_test))
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- CART:")
pred = metrics.confusion_matrix(y_test, clf_cart.predict(X_test))
y_pred_cart = clf_cart.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- Naive Bayes:")
pred = metrics.confusion_matrix(y_test, clf_bayes.predict(X_test))
y_pred_bayes = clf_bayes.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- RBF Kernel SVC:")
pred = metrics.confusion_matrix(y_test, clf_rbf.predict(X_test))
y_pred_svm = clf_rbf.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- Random Forest:")
pred = metrics.confusion_matrix(y_test, clf_forest.predict(X_test))
y_pred_forest = clf_forest.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- AdaBoost:")
pred = metrics.confusion_matrix(y_test, clf_boost.predict(X_test))
y_pred_boost = clf_boost.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

print("- MLP:")
pred = metrics.confusion_matrix(y_test, clf_mlp.predict(X_test))
y_pred_mlp = clf_mlp.predict(X_test)
GetMetrics(pred[1][1], pred[1][0], pred[0][0], pred[0][1])

from itertools import cycle

n_methods = 8
methods = ["KNN", "ID3", "CART", "Naive Bayes", "RBF Kernel SVC", "Random Forest", "AdaBoost", "MLP"]
colors = cycle(['navy', 'turquoise', 'darkorange', 'cornflowerblue', 'teal', 'red', 'orange', 'purple'])

from sklearn.metrics import roc_curve

fpr = dict()
tpr = dict()

fpr[0], tpr[0], _ = roc_curve(y_test, y_pred_knn)
fpr[1], tpr[1], _ = roc_curve(y_test, y_pred_id3)
fpr[2], tpr[2], _ = roc_curve(y_test, y_pred_cart)
fpr[3], tpr[3], _ = roc_curve(y_test, y_pred_bayes)
fpr[4], tpr[4], _ = roc_curve(y_test, y_pred_svm)
fpr[5], tpr[5], _ = roc_curve(y_test, y_pred_forest)
fpr[6], tpr[6], _ = roc_curve(y_test, y_pred_boost)
fpr[7], tpr[7], _ = roc_curve(y_test, y_pred_mlp)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import auc

plt.figure(figsize=(7, 8))
lines = []
labels = []

for i, color in zip(range(n_methods), colors):
    l, = plt.plot(fpr[i], tpr[i], color=color, lw=2)
    lines.append(l)
    labels.append('{0} (AUC = {1:0.2f})'.format(methods[i], auc(fpr[i], tpr[i])))

fig = plt.gcf()
fig.subplots_adjust(bottom=0.25)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('ROC curves')
plt.legend(lines, labels, loc=(.35, .1), prop=dict(size=14))

plt.show()

from sklearn.metrics import precision_recall_curve

precision = dict()
recall = dict()

precision[0], recall[0], _ = precision_recall_curve(y_test, y_pred_knn)
precision[1], recall[1], _ = precision_recall_curve(y_test, y_pred_id3)
precision[2], recall[2], _ = precision_recall_curve(y_test, y_pred_cart)
precision[3], recall[3], _ = precision_recall_curve(y_test, y_pred_bayes)
precision[4], recall[4], _ = precision_recall_curve(y_test, y_pred_svm)
precision[5], recall[5], _ = precision_recall_curve(y_test, y_pred_forest)
precision[6], recall[6], _ = precision_recall_curve(y_test, y_pred_boost)
precision[7], recall[7], _ = precision_recall_curve(y_test, y_pred_mlp)

plt.figure(figsize=(7, 8))
lines = []
labels = []

f_scores = np.linspace(0.2, 0.8, num=4)
for f_score in f_scores:
    x = np.linspace(0.01, 1)
    y = f_score * x / (2 * x - f_score)
    l, = plt.plot(x[y >= 0], y[y >= 0], color='gray', alpha=0.2)
    plt.annotate('f1={0:0.1f}'.format(f_score), xy=(0.9, y[45] + 0.02))
lines.append(l)
labels.append('iso-f1 curves')

for i, color in zip(range(n_methods), colors):
    l, = plt.plot(recall[i], precision[i], color=color, lw=2)
    lines.append(l)
    labels.append(methods[i])

fig = plt.gcf()
fig.subplots_adjust(bottom=0.25)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall curves')
plt.legend(lines, labels, loc=(.5, .2), prop=dict(size=14))

plt.show()